# Generated by Django 4.0 on 2022-06-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'verbose_name': 'Registro de tempo', 'verbose_name_plural': 'Registros de tempo'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuário'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='projects',
        ),
    ]
